POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzA2OTcyNDg1LCJ1c2VySWQiOjF9.CokT5wjg0uRNP8DTB7FnRIkreoQX54INSYv0sPIdwjE

{
    "nameofbook": "harrypotter3",
    "description": "A test book3"
}